apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: data-joiner
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: data-joiner
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Pods
      pods:
        metricName: kafka_consumer_consumer_fetch_manager_metrics_records_lag
        targetAverageValue: 10000
