prometheus:
  url: http://prometheus-operator-prometheus.default.svc
  port: 9090

rules:
  custom:
    - seriesQuery: '{__name__=~"kafka_consumer_consumer_fetch_manager_metrics_records_lag"}'
      resources:
        template: <<.Resource>>
      name:
        matches: "kafka_consumer_consumer_fetch_manager_metrics_records_lag"
        as: "kafka_consumer_lag_joiner"
      metricsQuery: 'kafka_consumer_consumer_fetch_manager_metrics_records_lag{<<.LabelMatchers>>, job="data-joiner", topic="geoWeather"} or kafka_consumer_consumer_fetch_manager_metrics_records_lag{<<.LabelMatchers>>, job="data-joiner", topic="hotels"}'
